// Generated from src/data/service-options.ts. Regenerate with scripts/gen-service-list.cjs.
// Used by edge functions to validate AI service_type suggestions.
export const SERVICE_NAMES: readonly string[] = [
 "220V Outlet Installation",
 "240V Outlet Installation",
 "AC Blower Motor Replacement",
 "AC Capacitor Replacement",
 "AC Cleaning",
 "AC Coil Cleaning",
 "AC Compressor Replacement",
 "AC Condensate Pump Installation",
 "AC Condensate Pump Replacement",
 "AC Contactor Replacement",
 "AC Control Board Replacement",
 "AC Drain Line Cleaning",
 "AC Drain Line Repair",
 "AC Fan Motor Replacement",
 "AC Maintenance",
 "AC Tune-Up",
 "ADU Construction",
 "ADU Remodeling",
 "ADU Repair",
 "AFCI Breaker Installation",
 "AFCI Outlet Installation",
 "Above-Ground Pool Installation",
 "Access Control Installation",
 "Access Panel Installation",
 "Accessibility Remodeling",
 "Accessible Bathroom Modification",
 "Accessible Cabinet Modification",
 "Accessible Shower Conversion",
 "Accessible Sink Installation",
 "Accessible Toilet Installation",
 "Accessory Building Construction",
 "Acoustic Panel Installation",
 "Acrylic Panel Installation",
 "Aging-in-Place Modification",
 "Air Balancing",
 "Air Compressor Installation",
 "Air Compressor Setup",
 "Air Conditioner Installation",
 "Air Conditioner Moving",
 "Air Conditioner Repair",
 "Air Conditioner Replacement",
 "Air Conditioner Tune-Up",
 "Air Duct Cleaning",
 "Air Duct Inspection",
 "Air Duct Repair",
 "Air Duct Replacement",
 "Air Duct Sealing",
 "Air Handler Repair",
 "Air Leak Testing",
 "Air Purifier Installation",
 "Air Quality Inspection",
 "Air Sealing",
 "Alarm System Repair",
 "Aluminum Fabrication",
 "Aluminum Fence Installation",
 "Aluminum Siding Repair",
 "Animal Entry Point Sealing",
 "Annual Home Maintenance",
 "Ant Control",
 "Apartment Moving",
 "Appliance Disposal",
 "Appliance Electrical Hookup",
 "Appliance Installation",
 "Appliance Pickup and Delivery",
 "Appliance Removal",
 "Appliance Repair",
 "Aquarium Bridge Installation",
 "Aquarium Installation",
 "Artificial Turf Cleaning",
 "Artificial Turf Installation",
 "Artificial Turf Maintenance",
 "Artificial Turf Removal",
 "Artificial Turf Repair",
 "Artificial Turf Replacement",
 "Artwork Installation",
 "Asbestos Inspection",
 "Asbestos Removal",
 "Asbestos Testing",
 "Asphalt Driveway Installation",
 "Asphalt Driveway Repair",
 "Asphalt Patching",
 "Asphalt Resurfacing",
 "Asphalt Roof Repair",
 "Attic Cleaning",
 "Attic Cleanout",
 "Attic Conversion",
 "Attic Debris Removal",
 "Attic Decontamination",
 "Attic Fan Installation",
 "Attic Fan Repair",
 "Attic Insulation Cleanup",
 "Attic Insulation Installation",
 "Attic Insulation Removal",
 "Attic Ladder Installation",
 "Attic Mold Removal",
 "Attic Rodent Cleanup",
 "Attic Sanitization",
 "Attic Ventilation Installation",
 "Attic Ventilation Repair",
 "Automatic Gate Installation",
 "Automatic Gate Repair",
 "Automatic Sliding Door Installation",
 "Automatic Sliding Door Repair",
 "Awning Cleaning",
 "Awning Fabric Replacement",
 "Awning Installation",
 "Awning Repair",
 "Backflow Irrigation Installation",
 "Backflow Irrigation Repair",
 "Backflow Preventer Installation",
 "Backflow Preventer Repair",
 "Backflow Preventer Testing",
 "Backsplash Installation",
 "Balcony Waterproofing",
 "Baluster Replacement",
 "Bamboo Removal",
 "Banister Repair",
 "Barn Door Installation",
 "Baseboard Heater Installation",
 "Baseboard Heater Repair",
 "Baseboard Heating Repair",
 "Baseboard Heating Replacement",
 "Baseboard Installation",
 "Basement Cleaning",
 "Basement Cleanout",
 "Basement Finishing",
 "Basement Flood Cleanup",
 "Basement Floor Repair",
 "Basement Foundation Repair",
 "Basement Insulation",
 "Basement Insulation Installation",
 "Basement Leak Repair",
 "Basement Remodeling",
 "Basement Repair",
 "Basement Wall Repair",
 "Basement Waterproofing",
 "Basement Window Installation",
 "Basement Window Replacement",
 "Basketball Hoop Assembly",
 "Basketball Hoop Installation",
 "Bat Removal",
 "Bathroom Caulking",
 "Bathroom Cleaning",
 "Bathroom Countertop Installation",
 "Bathroom Demolition",
 "Bathroom Drain Repair",
 "Bathroom Exhaust Fan Installation",
 "Bathroom Fan Venting",
 "Bathroom Grab Bar Replacement",
 "Bathroom Lighting Installation",
 "Bathroom Mirror Installation",
 "Bathroom Remodeling",
 "Bathroom Renovation",
 "Bathroom Repair",
 "Bathroom Safety Rail Installation",
 "Bathroom Sink Installation",
 "Bathroom Tile Installation",
 "Bathroom Tile Repair",
 "Bathroom Vanity Installation",
 "Bathroom Vanity Repair",
 "Bathroom Vent Installation",
 "Bathroom Vent Repair",
 "Bathroom Ventilation Upgrade",
 "Bathroom Waterproofing",
 "Bathtub Installation",
 "Bathtub Plumbing Repair",
 "Bathtub Refinishing",
 "Bathtub Reglazing",
 "Bathtub Repair",
 "Bathtub Resurfacing",
 "Batt Insulation Installation",
 "Battery Backup Installation",
 "Battery Backup Repair",
 "Battery Backup Replacement",
 "Bed Assembly",
 "Bed Bug Treatment",
 "Bee Removal",
 "Bidet Installation",
 "Bidet Repair",
 "Bidet Toilet Installation",
 "Bifold Door Installation",
 "Bifold Door Repair",
 "Biohazard Cleanup",
 "Bird Removal",
 "Black Mold Remediation",
 "Blind Cleaning",
 "Blind Installation",
 "Block Wall Installation",
 "Block Wall Repair",
 "Blower Door Testing",
 "Blown-In Insulation",
 "Boat Dock Repair",
 "Boat Flooring Installation",
 "Boiler Circulator Pump Repair",
 "Boiler Circulator Pump Replacement",
 "Boiler Installation",
 "Boiler Leak Repair",
 "Boiler Maintenance",
 "Boiler Repair",
 "Boiler Replacement",
 "Bookshelf Assembly",
 "Booster Pump Installation",
 "Booster Pump Repair",
 "Bowed Wall Repair",
 "Box Gutter Repair",
 "Box Gutter Replacement",
 "Breaker Panel Labeling",
 "Breaker Repair",
 "Brick Cleaning",
 "Brick Column Installation",
 "Brick Column Repair",
 "Brick Paint Removal",
 "Brick Painting",
 "Brick Pillar Installation",
 "Brick Pillar Repair",
 "Brick Repair",
 "Brick Replacement",
 "Brick Repointing",
 "Brick Veneer Repair",
 "Brick Wall Installation",
 "Brick Wall Repair",
 "Broken Window Glass Repair",
 "Brush Clearing",
 "Brush Removal",
 "Building Material Delivery",
 "Built-In Shelving Installation",
 "Burst Pipe Repair",
 "Bush Removal",
 "Bush Trimming",
 "Butcher Block Countertop Installation",
 "CMU Wall Installation",
 "CMU Wall Repair",
 "Cabinet Adjustment",
 "Cabinet Assembly",
 "Cabinet Demolition",
 "Cabinet Door Replacement",
 "Cabinet Hardware Installation",
 "Cabinet Hardware Replacement",
 "Cabinet Installation",
 "Cabinet Painting",
 "Cabinet Refacing",
 "Cabinet Refinishing",
 "Cabinet Repair",
 "Cable Concealment",
 "Canopy Cleaning",
 "Carbon Monoxide Detector Installation",
 "Carbon Monoxide Detector Testing",
 "Carpet Cleaning",
 "Carpet Disposal",
 "Carpet Dyeing",
 "Carpet Installation",
 "Carpet Odor Treatment",
 "Carpet Padding Replacement",
 "Carpet Patch Repair",
 "Carpet Pet Stain Treatment",
 "Carpet Removal",
 "Carpet Removal and Disposal",
 "Carpet Repair",
 "Carpet Seam Repair",
 "Carpet Stair Installation",
 "Carpet Stair Replacement",
 "Carpet Stretching",
 "Carpet Water Extraction",
 "Carport Installation",
 "Carport Repair",
 "Carport Replacement",
 "Catch Basin Cleaning",
 "Catch Basin Installation",
 "Catch Basin Repair",
 "Caulk Replacement",
 "Caulking",
 "Ceiling Crack Repair",
 "Ceiling Demolition",
 "Ceiling Fan Installation",
 "Ceiling Fan Repair",
 "Ceiling Painting",
 "Ceiling Repair",
 "Central Air Installation",
 "Central Air Repair",
 "Ceramic Tile Installation",
 "Chain-Link Fence Installation",
 "Chain-Link Fence Repair",
 "Chair Assembly",
 "Chair Rail Installation",
 "Chandelier Installation",
 "Channel Drain Installation",
 "Childproofing",
 "Chimney Cap Installation",
 "Chimney Cap Repair",
 "Chimney Cleaning",
 "Chimney Crown Repair",
 "Chimney Exterior Cleaning",
 "Chimney Flashing Repair",
 "Chimney Inspection",
 "Chimney Leak Repair",
 "Chimney Liner Installation",
 "Chimney Liner Repair",
 "Chimney Masonry Repair",
 "Chimney Rebuilding",
 "Chimney Repair",
 "Chimney Sweeping",
 "Chimney Waterproofing",
 "Circuit Breaker Replacement",
 "Circulation Pump Repair",
 "Circulation Pump Replacement",
 "Cleanout Installation",
 "Cleanout Repair",
 "Clogged Drain Repair",
 "Clogged Toilet Repair",
 "Closet Door Installation",
 "Closet Door Repair",
 "Closet Shelving Installation",
 "Coaxial Cable Installation",
 "Cockroach Control",
 "Combustion Safety Testing",
 "Commercial Appliance Cleaning",
 "Commercial Bathroom Remodeling",
 "Commercial Cooktop Repair",
 "Commercial Dishwasher Repair",
 "Commercial Door Installation",
 "Commercial Door Repair",
 "Commercial Drain Cleaning",
 "Commercial Dryer Repair",
 "Commercial Freezer Cleaning",
 "Commercial Freezer Repair",
 "Commercial Garage Door Installation",
 "Commercial Garage Door Repair",
 "Commercial Gutter Installation",
 "Commercial Gutter Repair",
 "Commercial HVAC Maintenance",
 "Commercial HVAC Repair",
 "Commercial Hood Cleaning",
 "Commercial Hood Installation",
 "Commercial Hood Repair",
 "Commercial Junk Removal",
 "Commercial Kitchen Deep Cleaning",
 "Commercial Kitchen Installation",
 "Commercial Kitchen Plumbing",
 "Commercial Kitchen Remodeling",
 "Commercial Laundry Equipment Repair",
 "Commercial Lighting Installation",
 "Commercial Lighting Repair",
 "Commercial Microwave Repair",
 "Commercial Oven Cleaning",
 "Commercial Oven Repair",
 "Commercial Plumbing Installation",
 "Commercial Plumbing Repair",
 "Commercial Pressure Washing",
 "Commercial Property Inspection",
 "Commercial Range Cleaning",
 "Commercial Range Repair",
 "Commercial Refrigeration Repair",
 "Commercial Refrigerator Cleaning",
 "Commercial Refrigerator Repair",
 "Commercial Restroom Installation",
 "Commercial Restroom Repair",
 "Commercial Sign Installation",
 "Commercial Sliding Door Repair",
 "Commercial Toilet Installation",
 "Commercial Toilet Repair",
 "Commercial Washer Repair",
 "Commercial Water Heater Installation",
 "Commercial Water Heater Repair",
 "Commercial Window Cleaning",
 "Composite Deck Board Replacement",
 "Composite Deck Installation",
 "Composite Deck Repair",
 "Concrete Cleaning",
 "Concrete Crack Repair",
 "Concrete Curb Installation",
 "Concrete Curb Repair",
 "Concrete Cutting",
 "Concrete Demolition",
 "Concrete Driveway Installation",
 "Concrete Driveway Resurfacing",
 "Concrete Epoxy Coating",
 "Concrete Expansion Joint Repair",
 "Concrete Floor Grinding",
 "Concrete Floor Polishing",
 "Concrete Footing Installation",
 "Concrete Footing Repair",
 "Concrete Foundation Installation",
 "Concrete Garage Slab Installation",
 "Concrete Grinding",
 "Concrete Hauling",
 "Concrete Joint Repair",
 "Concrete Leveling",
 "Concrete Lifting",
 "Concrete Mailbox Repair",
 "Concrete Pad Installation",
 "Concrete Paint Removal",
 "Concrete Painting",
 "Concrete Patio Installation",
 "Concrete Patio Repair",
 "Concrete Patio Resurfacing",
 "Concrete Pool Deck Repair",
 "Concrete Pool Deck Resurfacing",
 "Concrete Porch Installation",
 "Concrete Porch Repair",
 "Concrete Ramp Installation",
 "Concrete Removal",
 "Concrete Repair",
 "Concrete Resurfacing",
 "Concrete Sealing",
 "Concrete Shed Pad Installation",
 "Concrete Slab Installation",
 "Concrete Slab Repair",
 "Concrete Staining",
 "Concrete Step Installation",
 "Concrete Step Repair",
 "Concrete Wall Installation",
 "Concrete Wall Rebuilding",
 "Concrete Wall Repair",
 "Condensation Control",
 "Condenser Repair",
 "Construction Cleanup",
 "Construction Debris Hauling",
 "Construction Debris Removal",
 "Construction Progress Inspection",
 "Construction Project Management",
 "Contents Cleaning",
 "Contents Pack-Out",
 "Cooktop Repair",
 "Copper Pipe Repair",
 "Couch/Sofa Cleaning",
 "Countertop Installation",
 "Countertop Refinishing",
 "Countertop Reglazing",
 "Countertop Repair",
 "Countertop Resurfacing",
 "Countertop Support Repair",
 "Crawl Space Cleaning",
 "Crawl Space Debris Removal",
 "Crawl Space Decontamination",
 "Crawl Space Drainage",
 "Crawl Space Encapsulation",
 "Crawl Space Foundation Repair",
 "Crawl Space Inspection",
 "Crawl Space Insulation",
 "Crawl Space Mold Remediation",
 "Crawl Space Mold Removal",
 "Crawl Space Odor Removal",
 "Crawl Space Repair",
 "Crawl Space Sanitization",
 "Crawl Space Vent Repair",
 "Crawl Space Waterproofing",
 "Crown Molding Installation",
 "Culvert Installation",
 "Culvert Repair",
 "Curbless Shower Installation",
 "Curtain Installation",
 "Curtain Rod Installation",
 "Curtain Track Installation",
 "Custom Carpentry",
 "Custom Enclosure Fabrication",
 "Custom Glass Fabrication",
 "Custom Glass Installation",
 "Custom Metal Fabrication",
 "Custom Shelving",
 "Custom Storage Construction",
 "Custom Window Screen Installation",
 "Dead Animal Removal",
 "Deadbolt Installation",
 "Debris Hauling",
 "Deck Beam Replacement",
 "Deck Board Replacement",
 "Deck Cleaning",
 "Deck Demolition",
 "Deck Footing Installation",
 "Deck Footing Repair",
 "Deck Inspection",
 "Deck Inspection Report",
 "Deck Installation",
 "Deck Joist Replacement",
 "Deck Ledger Repair",
 "Deck Ledger Replacement",
 "Deck Leveling",
 "Deck Lifting",
 "Deck Paint Removal",
 "Deck Painting",
 "Deck Post Replacement",
 "Deck Railing Installation",
 "Deck Railing Repair",
 "Deck Refinishing",
 "Deck Reinforcement",
 "Deck Repair",
 "Deck Replacement",
 "Deck Resurfacing",
 "Deck Sealing",
 "Deck Staining",
 "Deck Stair Repair",
 "Deck Waterproofing",
 "Deck Waterproofing Membrane Installation",
 "Decorative Wall Panel Installation",
 "Dedicated Appliance Outlet Installation",
 "Dedicated Circuit Installation",
 "Deep Cleaning",
 "Dehumidification",
 "Dehumidifier Installation",
 "Demolition",
 "Demolition Cleanup",
 "Design-Build Service",
 "Desk Assembly",
 "Dimmer Switch Installation",
 "Dining Table Assembly",
 "Dirt Removal",
 "Disaster Board-Up Service",
 "Dishwasher Installation",
 "Dishwasher Repair",
 "Display Cooler Repair",
 "Dock Decking Repair",
 "Dock Installation",
 "Dock Repair",
 "Door Adjustment",
 "Door Alignment",
 "Door Closer Installation",
 "Door Closer Repair",
 "Door Draft Repair",
 "Door Frame Repair",
 "Door Framing",
 "Door Handle Installation",
 "Door Hinge Repair",
 "Door Installation",
 "Door Jamb Repair",
 "Door Lock Installation",
 "Door Lock Repair",
 "Door Painting",
 "Door Pickup and Installation",
 "Door Pivot Hinge Repair",
 "Door Pivot Hinge Replacement",
 "Door Refinishing",
 "Door Reinforcement",
 "Door Removal",
 "Door Repair",
 "Door Replacement",
 "Door Sweep Installation",
 "Door Threshold Replacement",
 "Door Weatherstripping",
 "Doorbell Repair",
 "Double-Pane Window Repair",
 "Downspout Cleaning",
 "Downspout Extension Installation",
 "Downspout Installation",
 "Downspout Repair",
 "Downspout Replacement",
 "Downspout Unclogging",
 "Draft Sealing",
 "Drain Cleaning",
 "Drain Pipe Installation",
 "Drain Pipe Repair",
 "Drain Pipe Replacement",
 "Drainage Correction",
 "Drainage Inspection",
 "Drainage Pond Repair",
 "Drainage Swale Installation",
 "Drainage System Installation",
 "Dresser Assembly",
 "Drip Irrigation Installation",
 "Drip Irrigation Repair",
 "Drip Line Installation",
 "Drip Line Repair",
 "Driveway Cleaning",
 "Driveway Drain Installation",
 "Driveway Drain Repair",
 "Driveway Drainage Correction",
 "Driveway Gate Installation",
 "Driveway Gate Repair",
 "Driveway Gate Security Installation",
 "Driveway Repair",
 "Driveway Sealcoating",
 "Drone Roof Inspection",
 "Dry Well Installation",
 "Dry Well Repair",
 "Dryer Hookup Installation",
 "Dryer Installation",
 "Dryer Repair",
 "Dryer Vent Booster Fan Installation",
 "Dryer Vent Cleaning",
 "Dryer Vent Installation",
 "Dryer Vent Repair",
 "Dryer Vent Rerouting",
 "Drywall Crack Repair",
 "Drywall Finishing",
 "Drywall Hole Repair",
 "Drywall Installation",
 "Drywall Patch Repair",
 "Drywall Patching",
 "Drywall Repair",
 "Drywall Replacement",
 "Drywall Seam Repair",
 "Drywall Tape Repair",
 "Drywall Texturing",
 "Duct Balancing",
 "Duct Boot Repair",
 "Duct Boot Replacement",
 "Duct Insulation",
 "Duct Leakage Testing",
 "Duct Modification",
 "Duct Plenum Repair",
 "Duct Plenum Replacement",
 "Duct Relocation",
 "Ductless Mini-Split Installation",
 "Ductless Mini-Split Repair",
 "Ductwork Installation",
 "Ductwork Replacement",
 "Dumbwaiter Installation",
 "Dumbwaiter Repair",
 "Dumpster Pad Cleaning",
 "EV Charger Installation",
 "EV Charger Outlet Installation",
 "EV Charger Repair",
 "EV Charger Troubleshooting",
 "Earthquake Retrofitting",
 "Efflorescence Cleaning",
 "Efflorescence Removal",
 "Egress Window Installation",
 "Electric Appliance Hookup",
 "Electric Dryer Hookup",
 "Electric Fireplace Installation",
 "Electric Gate Installation",
 "Electric Gate Repair",
 "Electric Heater Repair",
 "Electric Water Heater Repair",
 "Electrical Arc Fault Repair",
 "Electrical Bonding",
 "Electrical Bus Bar Repair",
 "Electrical Bus Bar Replacement",
 "Electrical Circuit Installation",
 "Electrical Code Correction",
 "Electrical Fault Finding",
 "Electrical Ground Rod Installation",
 "Electrical Grounding Repair",
 "Electrical Inspection",
 "Electrical Load Calculation",
 "Electrical Load Troubleshooting",
 "Electrical Load Upgrade",
 "Electrical Meter Repair",
 "Electrical Neutral Repair",
 "Electrical Panel Repair",
 "Electrical Panel Replacement",
 "Electrical Panel Upgrade",
 "Electrical Permit Inspection",
 "Electrical Permit Sign-Off",
 "Electrical Safety Inspection",
 "Electrical Service Installation",
 "Electrical Service Replacement",
 "Electrical Service Upgrade",
 "Electrical Short Circuit Repair",
 "Electrical Subpanel Installation",
 "Electrical Subpanel Repair",
 "Electrical Subpanel Replacement",
 "Electrical Switch Repair",
 "Electrical Troubleshooting",
 "Electrical Wiring Installation",
 "Electrical Wiring Repair",
 "Electrical Wiring Replacement",
 "Elevator Repair",
 "Emergency Electrical Repair",
 "Emergency HVAC Repair",
 "Emergency Light Installation",
 "Emergency Light Repair",
 "Emergency Locksmith",
 "Emergency Plumbing",
 "Emergency Roof Repair",
 "Emergency Tarping",
 "Emergency Tree Removal",
 "Emergency Water Damage Restoration",
 "Energy Audit",
 "Energy Efficiency Inspection",
 "Energy-Efficient Door Installation",
 "Energy-Efficient Window Installation",
 "Engineered Wood Flooring Installation",
 "Entry Door Repair",
 "Epoxy Floor Coating",
 "Erosion Control",
 "Estate Cleanout",
 "Ethernet Cable Installation",
 "Ethernet Wiring",
 "Eufy Permanent Light Installation",
 "Evaporator Coil Replacement",
 "Excavation",
 "Exercise Bike Assembly",
 "Exercise Equipment Moving",
 "Exit Sign Installation",
 "Exit Sign Repair",
 "Expansion Tank Installation",
 "Expansion Tank Replacement",
 "Exterior Caulking",
 "Exterior Demolition",
 "Exterior Door Installation",
 "Exterior Faucet Winterization",
 "Exterior Mildew Removal",
 "Exterior Mold Removal",
 "Exterior Painting",
 "Exterior Trim Repair",
 "Exterior Wall Leak Repair",
 "Exterior Waterproofing",
 "Exterior Window Cleaning",
 "Fall Cleanup",
 "Fall Home Maintenance",
 "Fascia Repair",
 "Fascia Replacement",
 "Faucet Installation",
 "Faucet Repair",
 "Faucet Replacement",
 "Fence Board Replacement",
 "Fence Cleaning",
 "Fence Demolition",
 "Fence Extension",
 "Fence Gate Alignment",
 "Fence Gate Relocation",
 "Fence Gate Replacement",
 "Fence Height Extension",
 "Fence Inspection",
 "Fence Installation",
 "Fence Paint Removal",
 "Fence Painting",
 "Fence Panel Replacement",
 "Fence Post Repair",
 "Fence Post Replacement",
 "Fence Pressure Washing",
 "Fence Railing Repair",
 "Fence Reinforcement",
 "Fence Removal",
 "Fence Repair",
 "Fence Replacement",
 "Fence Staining",
 "Fiber Cement Siding Installation",
 "Fiber Cement Siding Repair",
 "Fiberglass Refinishing",
 "Fiberglass Shower Repair",
 "Fiberglass Tub Repair",
 "Fill Dirt Installation",
 "Finish Carpentry",
 "Fire Alarm Inspection",
 "Fire Alarm Installation",
 "Fire Alarm Panel Repair",
 "Fire Alarm Panel Replacement",
 "Fire Alarm Repair",
 "Fire Damage Reconstruction",
 "Fire Damage Restoration",
 "Fire Debris Removal",
 "Fire Pit Installation",
 "Fire Pit Repair",
 "Fire Sprinkler Head Replacement",
 "Fire Sprinkler Inspection",
 "Fire Sprinkler Installation",
 "Fire Sprinkler Repair",
 "Fireplace Chimney Relining",
 "Fireplace Cleaning",
 "Fireplace Damper Repair",
 "Fireplace Damper Replacement",
 "Fireplace Door Installation",
 "Fireplace Glass Replacement",
 "Fireplace Ignitor Repair",
 "Fireplace Insert Installation",
 "Fireplace Inspection",
 "Fireplace Inspection Certification",
 "Fireplace Installation",
 "Fireplace Masonry Repair",
 "Fireplace Pilot Light Repair",
 "Fireplace Repair",
 "Fireplace Tile Installation",
 "Fireplace Tile Repair",
 "Fitness Equipment Assembly",
 "Flagpole Installation",
 "Flat Roof Repair",
 "Flea Treatment",
 "Flood Cleanup",
 "Floor Buffing",
 "Floor Drain Installation",
 "Floor Drain Repair",
 "Floor Joist Repair",
 "Floor Leveling",
 "Floor Stripping and Waxing",
 "Floor Transition Installation",
 "Floor Water Damage Repair",
 "Floor Waxing",
 "Flooring Demolition",
 "Flooring Inspection",
 "Flooring Installation",
 "Flooring Repair",
 "Flooring Replacement",
 "Flower Bed Installation",
 "Flower Bed Maintenance",
 "Flower Bed Restoration",
 "Fogged Window Repair",
 "Foreclosure Cleanup",
 "Foundation Crack Repair",
 "Foundation Drain Installation",
 "Foundation Drain Repair",
 "Foundation Drainage Installation",
 "Foundation Elevation Survey",
 "Foundation Inspection",
 "Foundation Leak Repair",
 "Foundation Pier Installation",
 "Foundation Repair",
 "Foundation Waterproofing",
 "Fountain Cleaning",
 "Fountain Installation",
 "Fountain Maintenance",
 "Fountain Pump Replacement",
 "Fountain Repair",
 "Four-Point Home Inspection",
 "Framing Repair",
 "Freeze Protection",
 "Freezer Repair",
 "French Door Installation",
 "French Door Repair",
 "French Drain Installation",
 "French Drain Repair",
 "Front Door Installation",
 "Frozen Pipe Repair",
 "Furnace Blower Motor Replacement",
 "Furnace Cleaning",
 "Furnace Control Board Replacement",
 "Furnace Heat Exchanger Replacement",
 "Furnace Ignitor Replacement",
 "Furnace Installation",
 "Furnace Maintenance",
 "Furnace Repair",
 "Furnace Replacement",
 "Furnace Tune-Up",
 "Furniture Assembly",
 "Furniture Delivery",
 "Furniture Disassembly",
 "Furniture Disposal",
 "Furniture Moving",
 "Furniture Reassembly",
 "Furniture Removal",
 "Furniture Repair",
 "Fuse Box Replacement",
 "GFCI Breaker Installation",
 "GFCI Breaker Replacement",
 "GFCI Outlet Installation",
 "Gable Vent Installation",
 "Gable Vent Repair",
 "Garage Addition",
 "Garage Cabinet Installation",
 "Garage Cleaning",
 "Garage Cleanout",
 "Garage Construction",
 "Garage Conversion",
 "Garage Conversion Repair",
 "Garage Door Alignment",
 "Garage Door Belt Replacement",
 "Garage Door Bottom Seal Replacement",
 "Garage Door Cable Repair",
 "Garage Door Chain Replacement",
 "Garage Door Conversion",
 "Garage Door Drum Repair",
 "Garage Door Extension Spring Replacement",
 "Garage Door Installation",
 "Garage Door Insulation",
 "Garage Door Keypad Installation",
 "Garage Door Keypad Repair",
 "Garage Door Maintenance",
 "Garage Door Opener Installation",
 "Garage Door Opener Repair",
 "Garage Door Panel Replacement",
 "Garage Door Remote Programming",
 "Garage Door Remote Repair",
 "Garage Door Repair",
 "Garage Door Replacement",
 "Garage Door Roller Replacement",
 "Garage Door Sensor Repair",
 "Garage Door Sensor Replacement",
 "Garage Door Side Seal Replacement",
 "Garage Door Spring Replacement",
 "Garage Door Threshold Installation",
 "Garage Door Top Seal Replacement",
 "Garage Door Torsion Spring Replacement",
 "Garage Door Track Repair",
 "Garage Door Tune-Up",
 "Garage Door Weatherstripping",
 "Garage Entry Door Installation",
 "Garage Floor Cleaning",
 "Garage Floor Coating",
 "Garage Floor Epoxy",
 "Garage Floor Leveling",
 "Garage Floor Polyaspartic Coating",
 "Garage Floor Refinishing",
 "Garage Floor Repair",
 "Garage Floor Resurfacing",
 "Garage Insulation",
 "Garage Lighting Installation",
 "Garage Remodeling",
 "Garage Repair",
 "Garage Shelving Installation",
 "Garage Storage Installation",
 "Garage Ventilation Installation",
 "Garbage Disposal Installation",
 "Garbage Disposal Repair",
 "Garden Bed Installation",
 "Garden Soil Installation",
 "Gas Appliance Hookup",
 "Gas Dryer Hookup",
 "Gas Fire Pit Installation",
 "Gas Fire Pit Repair",
 "Gas Fireplace Cleaning",
 "Gas Fireplace Installation",
 "Gas Fireplace Maintenance",
 "Gas Fireplace Repair",
 "Gas Grill Installation",
 "Gas Grill Repair",
 "Gas Heater Repair",
 "Gas Leak Detection",
 "Gas Line Installation",
 "Gas Line Repair",
 "Gas Log Installation",
 "Gas Water Heater Repair",
 "Gate Access Control Installation",
 "Gate Access Control Repair",
 "Gate Installation",
 "Gate Motor Repair",
 "Gate Motor Replacement",
 "Gate Opener Repair",
 "Gate Remote Programming",
 "Gate Repair",
 "Gate Sensor Installation",
 "Gate Sensor Repair",
 "Gazebo Anchoring",
 "Gazebo Assembly",
 "Gazebo Installation",
 "Gazebo Relocation",
 "Gazebo Removal",
 "Gazebo Repair",
 "General Carpentry",
 "General Electrical Repair",
 "General Handyman Service",
 "General Home Inspection",
 "General Landscaping",
 "General Pest Control",
 "General Plumbing Repair",
 "General Remodeling",
 "Generator Inlet Installation",
 "Generator Installation",
 "Generator Interlock Installation",
 "Generator Interlock Repair",
 "Generator Maintenance",
 "Generator Repair",
 "Generator Transfer Switch Installation",
 "Generator Transfer Switch Repair",
 "Geogrid Driveway Installation",
 "Glass Cutting",
 "Glass Door Installation",
 "Glass Door Repair",
 "Glass Tint Removal",
 "Govee Light Installation",
 "Govee Light Repair",
 "Govee Light Troubleshooting",
 "Grab Bar Installation",
 "Grading and Drainage Correction",
 "Graffiti Paint Removal",
 "Graffiti Removal",
 "Granite Countertop Repair",
 "Grass Seeding",
 "Gravel Driveway Installation",
 "Gravel Driveway Repair",
 "Grease Trap Cleaning",
 "Grease Trap Installation",
 "Grease Trap Repair",
 "Grease Waste Plumbing Installation",
 "Grounding Electrode Installation",
 "Grout Cleaning",
 "Grout Repair",
 "Grout Replacement",
 "Grout Sealing",
 "Gutter Cleaning",
 "Gutter Corner Repair",
 "Gutter End Cap Repair",
 "Gutter Guard Cleaning",
 "Gutter Guard Installation",
 "Gutter Hanger Installation",
 "Gutter Hanger Replacement",
 "Gutter Installation",
 "Gutter Joint Repair",
 "Gutter Leak Repair",
 "Gutter Pitch Correction",
 "Gutter Realignment",
 "Gutter Repair",
 "Gutter Replacement",
 "Gutter Resealing",
 "Gutter Whitening",
 "HVAC Filter Replacement",
 "HVAC Inspection",
 "HVAC Maintenance",
 "HVAC Permit Inspection",
 "HVAC Seasonal Tune-Up",
 "HVAC Tune-Up",
 "HVAC Zoning System Installation",
 "Hail Damage Repair",
 "Handrail Installation",
 "Handrail Repair",
 "Handyman Estimate Visit",
 "Hard Water Stain Removal",
 "Hardscape Installation",
 "Hardscape Repair",
 "Hardware Replacement",
 "Hardwood Floor Cleaning",
 "Hardwood Floor Installation",
 "Hardwood Floor Refinishing",
 "Hardwood Floor Repair",
 "Hardwood Floor Sanding",
 "Hazardous Tree Removal",
 "Heat Pump Installation",
 "Heat Pump Repair",
 "Heat Pump Replacement",
 "Heat Pump Water Heater Installation",
 "Heat Pump Water Heater Repair",
 "Heavy Appliance Moving",
 "Heavy Item Lifting",
 "Hedge Trimming",
 "High-Bay Light Installation",
 "High-Bay Light Repair",
 "High-Rise Window Cleaning",
 "Hoarding Cleanup",
 "Holiday Light Installation",
 "Holiday Light Removal",
 "Home Accessibility Assessment",
 "Home Addition",
 "Home Alarm Installation",
 "Home Automation Hub Setup",
 "Home Battery Backup Installation",
 "Home Battery Maintenance",
 "Home De-Winterization",
 "Home Energy Audit",
 "Home Gym Assembly",
 "Home Maintenance Service",
 "Home Office Construction",
 "Home Punch-List Completion",
 "Home Repair Inspection",
 "Home Surge Protector Installation",
 "Home Theater Installation",
 "Home Theater Wiring",
 "Home Winterization",
 "Hose Bib Replacement",
 "Hot Mop Shower Pan Installation",
 "Hot Tub Cleaning",
 "Hot Tub Control Board Repair",
 "Hot Tub Control Panel Repair",
 "Hot Tub Disconnect Installation",
 "Hot Tub Disconnect Repair",
 "Hot Tub Disposal",
 "Hot Tub Electrical Hookup",
 "Hot Tub GFCI Troubleshooting",
 "Hot Tub Hauling",
 "Hot Tub Heater Repair",
 "Hot Tub Inspection",
 "Hot Tub Installation",
 "Hot Tub Jet Repair",
 "Hot Tub Maintenance",
 "Hot Tub Plumbing Repair",
 "Hot Tub Pump Replacement",
 "Hot Tub Relocation",
 "Hot Tub Removal",
 "Hot Tub Repair",
 "Hot Tub Replacement",
 "Hot Tub Winterization",
 "Hot Water Recirculation Pump Installation",
 "House Leveling",
 "House Number Installation",
 "House Washing",
 "House Wrap Installation",
 "Hurricane Preparation",
 "Hybrid Water Heater Installation",
 "Hydro Jetting",
 "Hydronic Heating Installation",
 "Hydronic Heating Repair",
 "Ice Dam Prevention",
 "Ice Dam Removal",
 "Ice Machine Installation",
 "Ice Machine Repair",
 "Ice Maker Repair",
 "Indoor Air Quality Testing",
 "Indoor Lighting Installation",
 "Indoor Lighting Repair",
 "Infrared Leak Detection",
 "Insulated Glass Replacement",
 "Insulation Inspection",
 "Intercom Installation",
 "Interior Demolition",
 "Interior Door Installation",
 "Interior Drain Tile Installation",
 "Interior Painting",
 "Interior Strip-Out",
 "Interior Wall Removal",
 "Interior Waterproofing",
 "Irrigation Controller Programming",
 "Irrigation Installation",
 "Irrigation Repair",
 "Irrigation Valve Location",
 "Irrigation Wire Repair",
 "Irrigation Wire Tracing",
 "Junk Removal",
 "Keypad Lock Installation",
 "Kitchen Cabinet Installation",
 "Kitchen Cabinet Repair",
 "Kitchen Cleaning",
 "Kitchen Demolition",
 "Kitchen Drain Repair",
 "Kitchen Electrical Upgrades",
 "Kitchen Exhaust Fan Installation",
 "Kitchen Exhaust Vent Repair",
 "Kitchen Faucet Installation",
 "Kitchen Hood Venting",
 "Kitchen Island Installation",
 "Kitchen Plumbing Relocation",
 "Kitchen Remodeling",
 "Kitchen Renovation",
 "Kitchen Repair",
 "Kitchen Sink Installation",
 "Kitchen Tile Installation",
 "LED Strip Light Installation",
 "Laminate Countertop Repair",
 "Laminate Flooring Installation",
 "Laminate Flooring Repair",
 "Lanai Screen Installation",
 "Lanai Screen Repair",
 "Land Clearing",
 "Landscape Cleanup",
 "Landscape Design",
 "Landscape Drainage Installation",
 "Landscape Drainage Repair",
 "Landscape Edging",
 "Landscape Fabric Installation",
 "Landscape Grading",
 "Landscape Lighting Installation",
 "Landscape Lighting Repair",
 "Landscape Maintenance",
 "Landscape Renovation",
 "Landscape Rock Removal",
 "Landscape Rock Replacement",
 "Laundry Drain Installation",
 "Laundry Drain Repair",
 "Laundry Hookup Installation",
 "Laundry Hookup Relocation",
 "Laundry Room Remodeling",
 "Laundry Sink Installation",
 "Lawn Aeration",
 "Lawn Dethatching",
 "Lawn Disease Treatment",
 "Lawn Fertilization",
 "Lawn Leveling",
 "Lawn Mowing",
 "Lawn Overseeding",
 "Lawn Pest Control",
 "Lawn Repair",
 "Lawn Sprinkler Blowout",
 "Lawn Top Dressing",
 "Lead Dust Testing",
 "Lead Paint Removal",
 "Lead Paint Testing",
 "Lead-Safe Painting",
 "Leader Installation",
 "Leader Replacement",
 "Leaf Guard Repair",
 "Leaf Guard Replacement",
 "Leaf Removal",
 "Leak Moisture Testing",
 "Letterbox Construction",
 "Lever Door Handle Installation",
 "Light Fixture Replacement",
 "Light Switch Installation",
 "Linoleum Installation",
 "Load-Bearing Wall Repair",
 "Local Moving Service",
 "Lock Rekeying",
 "Lock Repair",
 "Lock Replacement",
 "Lot Clearing",
 "Low-Voltage Landscape Lighting Installation",
 "Low-Voltage Landscape Lighting Repair",
 "Low-Voltage Wiring",
 "Luxury Vinyl Plank Installation",
 "Mailbox Installation",
 "Mailbox Post Repair",
 "Mailbox Post Replacement",
 "Mailbox Repair",
 "Mailbox Reset",
 "Main Disconnect Installation",
 "Main Disconnect Replacement",
 "Main Sewer Line Cleaning",
 "Main Water Shutoff Installation",
 "Make-Up Air System Installation",
 "Make-Up Air System Repair",
 "Marble Polishing",
 "Marble Restoration",
 "Marine Flooring Installation",
 "Masonry Installation",
 "Masonry Repair",
 "Material Pickup and Delivery",
 "Mattress Disposal",
 "Medicine Cabinet Installation",
 "Mesh Wi-Fi Installation",
 "Metal Fence Repair",
 "Metal Roof Repair",
 "Meter Base Installation",
 "Meter Base Replacement",
 "Methamphetamine Testing",
 "Microwave Installation",
 "Microwave Repair",
 "Mini-Split Cleaning",
 "Mini-Split Compressor Replacement",
 "Mini-Split Drain Repair",
 "Mini-Split Maintenance",
 "Mini-Split Refrigerant Leak Repair",
 "Mini-Split Refrigerant Recharge",
 "Mini-Split Relocation",
 "Minor Home Repairs",
 "Mirror Cutting",
 "Mirror Framing",
 "Mirror Hanging",
 "Mirror Mounting",
 "Mirror Repair",
 "Mirror Replacement",
 "Moisture Barrier Installation",
 "Moisture Inspection",
 "Moisture Mapping",
 "Mold Encapsulation",
 "Mold Inspection",
 "Mold Prevention Treatment",
 "Mold Remediation",
 "Mold Removal",
 "Mold Surface Treatment",
 "Mold Testing",
 "Mortar Repair",
 "Mosquito Control",
 "Moss Removal",
 "Motion Detector Installation",
 "Motion Sensor Light Installation",
 "Motion-Activated Lighting Installation",
 "Motorized Blind Installation",
 "Motorized Blind Repair",
 "Mouse Removal",
 "Move-In Cleaning",
 "Move-Out Cleaning",
 "Moving Help",
 "Mudroom Installation",
 "Mulch Installation",
 "Natural Stone Flooring Installation",
 "Natural Stone Sealing",
 "New Construction Inspection",
 "New Roof Installation",
 "Non-Load-Bearing Wall Removal",
 "Non-Slip Flooring Installation",
 "Odor Removal",
 "Office Cleanout",
 "Oil Stain Removal",
 "Open-Concept Conversion",
 "Outbuilding Construction",
 "Outdoor Drain Cleaning",
 "Outdoor Faucet Repair",
 "Outdoor Fireplace Installation",
 "Outdoor Fireplace Repair",
 "Outdoor Kitchen Installation",
 "Outdoor Kitchen Repair",
 "Outdoor Lighting Installation",
 "Outdoor Security Lighting",
 "Outdoor Shower Installation",
 "Outdoor Shower Repair",
 "Outlet Grounding",
 "Outlet Installation",
 "Outlet Repair",
 "Oven Repair",
 "P-Trap Replacement",
 "PEX Pipe Installation",
 "PTAC Installation",
 "PTAC Repair",
 "PVC Pipe Repair",
 "Packaged HVAC Unit Installation",
 "Packaged HVAC Unit Repair",
 "Packing Service",
 "Paint Removal",
 "Paint Stripping",
 "Paint Touch-Up",
 "Palm Tree Removal",
 "Palm Tree Trimming",
 "Pantry Installation",
 "Parking Lot Lighting Installation",
 "Parking Lot Lighting Repair",
 "Parking Lot Pressure Washing",
 "Parking Lot Repair",
 "Parking Lot Sealcoating",
 "Parking Lot Striping",
 "Partition Wall Installation",
 "Patio Cleaning",
 "Patio Cover Installation",
 "Patio Cover Repair",
 "Patio Cover Replacement",
 "Patio Demolition",
 "Patio Door Repair",
 "Patio Enclosure Installation",
 "Patio Enclosure Repair",
 "Patio Furniture Assembly",
 "Patio Heater Installation",
 "Patio Heater Repair",
 "Patio Installation",
 "Patio Repair",
 "Paver Cleaning",
 "Paver Driveway Installation",
 "Paver Driveway Repair",
 "Paver Installation",
 "Paver Joint Sanding",
 "Paver Leveling",
 "Paver Patio Installation",
 "Paver Patio Repair",
 "Paver Polymeric Sand Installation",
 "Paver Releveling",
 "Paver Repair",
 "Paver Sealing",
 "Paver Walkway Installation",
 "Paver Walkway Repair",
 "Pea Gravel Installation",
 "Pendant Light Installation",
 "Pergola Assembly",
 "Pergola Installation",
 "Pergola Repair",
 "Permanent Christmas Light Installation",
 "Permanent Christmas Light Repair",
 "Permanent Outdoor Light Installation",
 "Permanent Outdoor Light Programming",
 "Permanent Outdoor Light Repair",
 "Permanent Outdoor Light Troubleshooting",
 "Permit Assistance",
 "Permit Assistance for ADU Construction",
 "Permit Assistance for Deck Construction",
 "Permit Assistance for Demolition",
 "Permit Assistance for Electrical Work",
 "Permit Assistance for Fence Installation",
 "Permit Assistance for HVAC Work",
 "Permit Assistance for Plumbing Work",
 "Permit Assistance for Pool Work",
 "Permit Assistance for Remodeling",
 "Pest Inspection",
 "Pet Door Installation",
 "Pet Stain Removal",
 "Piano Moving",
 "Picket Fence Installation",
 "Picture Hanging",
 "Pier and Beam Repair",
 "Pipe Insulation",
 "Pipe Leak Repair",
 "Pipe Replacement",
 "Plaster Installation",
 "Plaster Repair",
 "Platform Lift Installation",
 "Platform Lift Repair",
 "Playset Assembly",
 "Plexiglass Installation",
 "Plumbing Inspection",
 "Plumbing Permit Inspection",
 "Plumbing Winterization",
 "Pocket Door Installation",
 "Pocket Door Repair",
 "Pocket Door Track Repair",
 "Pole Barn Construction",
 "Pole Light Installation",
 "Pole Light Repair",
 "Polyaspartic Floor Coating",
 "Pond Cleaning",
 "Pond Installation",
 "Pond Liner Repair",
 "Pond Liner Replacement",
 "Pond Maintenance",
 "Pond Pump Repair",
 "Pond Pump Replacement",
 "Pond Repair",
 "Pool Acid Washing",
 "Pool Automation System Installation",
 "Pool Automation System Repair",
 "Pool Bonding Installation",
 "Pool Bonding Repair",
 "Pool Chemical Balancing",
 "Pool Cleaning",
 "Pool Coping Installation",
 "Pool Coping Repair",
 "Pool Cover Installation",
 "Pool Deck Cleaning",
 "Pool Deck Construction",
 "Pool Deck Repair",
 "Pool Deck Replacement",
 "Pool Deck Resurfacing",
 "Pool Deck Sealing",
 "Pool Demolition",
 "Pool Drain and Refill",
 "Pool Electrical Inspection",
 "Pool Electrical Repair",
 "Pool Expansion Joint Repair",
 "Pool Fence Installation",
 "Pool Fence Repair",
 "Pool Filter Repair",
 "Pool Filter Replacement",
 "Pool Gate Installation",
 "Pool Gate Repair",
 "Pool Heater Installation",
 "Pool Heater Repair",
 "Pool Inspection",
 "Pool Installation",
 "Pool Leak Detection",
 "Pool Leak Repair",
 "Pool Light Repair",
 "Pool Liner Installation",
 "Pool Liner Replacement",
 "Pool Maintenance",
 "Pool Opening Service",
 "Pool Plumbing Repair",
 "Pool Pump Installation",
 "Pool Pump Repair",
 "Pool Removal",
 "Pool Repair",
 "Pool Resurfacing",
 "Pool Safety Cover Installation",
 "Pool Saltwater System Repair",
 "Pool Skimmer Repair",
 "Pool Table Assembly",
 "Pool Table Moving",
 "Pool Tile Repair",
 "Pool Winterization",
 "Popcorn Ceiling Removal",
 "Popcorn Ceiling Repair",
 "Porcelain Tile Installation",
 "Porch Column Repair",
 "Porch Installation",
 "Porch Railing Installation",
 "Porch Repair",
 "Porch Rescreening",
 "Porch Screening",
 "Portable Generator Hookup",
 "Post-Construction Cleaning",
 "Post-Construction Window Cleaning",
 "Power Outage Diagnosis",
 "Pre-Listing Home Inspection",
 "Pre-Purchase Home Inspection",
 "Pressure Tank Installation",
 "Pressure Tank Repair",
 "Pressure Washing",
 "Pressure Washing Before Painting",
 "Preventive Maintenance Plan",
 "Privacy Fence Installation",
 "Privacy Film Installation",
 "Property Maintenance Inspection",
 "Property Preservation Service",
 "Quartz Countertop Repair",
 "Raccoon Removal",
 "Radiant Barrier Installation",
 "Radiant Floor Heating Installation",
 "Radiant Floor Heating Repair",
 "Radiator Repair",
 "Radon Mitigation",
 "Radon System Installation",
 "Radon System Repair",
 "Radon Testing",
 "Rain Chain Installation",
 "Rain Gutter Inspection",
 "Raised Toilet Installation",
 "Range Hood Duct Installation",
 "Range Hood Duct Repair",
 "Range Hood Installation",
 "Range Hood Repair",
 "Range Repair",
 "Rat Removal",
 "Reach-In Cooler Repair",
 "Recessed Lighting Installation",
 "Recliner Assembly",
 "Refrigerant Leak Repair",
 "Refrigerant Recharge",
 "Refrigeration Compressor Replacement",
 "Refrigeration Condenser Repair",
 "Refrigeration Evaporator Repair",
 "Refrigeration Leak Repair",
 "Refrigerator Repair",
 "Register Replacement",
 "Regrouting",
 "Renovation Cleanup",
 "Rental Make-Ready Service",
 "Rental Property Inspection",
 "Rental Property Turnover Repairs",
 "Rental Turnover Cleaning",
 "Rental Turnover Maintenance",
 "Residential Elevator Repair",
 "Residential Lockout Service",
 "Residential Moving",
 "Restaurant Kitchen Installation",
 "Restaurant Plumbing Installation",
 "Restoration Reconstruction",
 "Retaining Wall Drainage Installation",
 "Retaining Wall Installation",
 "Retaining Wall Rebuilding",
 "Retaining Wall Repair",
 "Retaining Wall Replacement",
 "Return Air Installation",
 "Return-Air Vent Installation",
 "Reverse Osmosis System Installation",
 "Ridge Vent Installation",
 "Rim Joist Repair",
 "River Rock Installation",
 "Rock Installation",
 "Rodent Control",
 "Rodent Exclusion",
 "Roll-Up Door Installation",
 "Roll-Up Door Repair",
 "Roof Certification",
 "Roof Certification Inspection",
 "Roof Cleaning",
 "Roof Coating",
 "Roof Cricket Installation",
 "Roof Debris Removal",
 "Roof Deck Repair",
 "Roof Deck Replacement",
 "Roof Drain Cleaning",
 "Roof Drain Repair",
 "Roof Drip Edge Installation",
 "Roof Drip Edge Repair",
 "Roof Fascia Painting",
 "Roof Flashing Repair",
 "Roof Inspection",
 "Roof Leak Detection",
 "Roof Leak Repair",
 "Roof Maintenance",
 "Roof Moisture Inspection",
 "Roof Pressure Washing",
 "Roof Rejuvenation",
 "Roof Replacement",
 "Roof Replacement Inspection",
 "Roof Sealing",
 "Roof Sheathing Repair",
 "Roof Sheathing Replacement",
 "Roof Shingle Sealing",
 "Roof Snow Removal",
 "Roof Soft Washing",
 "Roof Storm Damage Repair",
 "Roof Tarp Installation",
 "Roof Tear-Off",
 "Roof Truss Reinforcement",
 "Roof Truss Repair",
 "Roof Tune-Up",
 "Roof Vent Installation",
 "Roof Vent Repair",
 "Roof Ventilation Improvement",
 "Roof Waterproofing",
 "Rooftop HVAC Unit Installation",
 "Rooftop HVAC Unit Repair",
 "Room Addition",
 "Room Painting",
 "Rough Carpentry",
 "Rubber Roof Repair",
 "Rug Cleaning",
 "Running Toilet Repair",
 "Rust Removal",
 "Rust Stain Removal",
 "Safe Installation",
 "Safe Moving",
 "Safe Opening",
 "Sagging Ceiling Repair",
 "Satellite Dish Removal",
 "Sauna Installation",
 "Sauna Repair",
 "Screen Door Installation",
 "Screen Door Repair",
 "Screen Enclosure Installation",
 "Screen Enclosure Repair",
 "Screen Repair",
 "Screen Room Installation",
 "Screen Room Repair",
 "Screened Porch Installation",
 "Screened Porch Repair",
 "Seamless Gutter Installation",
 "Security Camera Installation",
 "Security Film Installation",
 "Security Lighting Installation",
 "Security System Installation",
 "Septic Aerator Installation",
 "Septic Aerator Repair",
 "Septic Drain Field Repair",
 "Septic Drain Field Replacement",
 "Septic Line Repair",
 "Septic Line Replacement",
 "Septic Pump Installation",
 "Septic Pump Repair",
 "Septic System Cleaning",
 "Septic System Installation",
 "Septic System Maintenance",
 "Septic System Repair",
 "Septic Tank Inspection",
 "Septic Tank Pumping",
 "Septic Tank Repair",
 "Septic Tank Replacement",
 "Service Entrance Cable Repair",
 "Service Entrance Cable Replacement",
 "Sewage Cleanup",
 "Sewage Ejector Pump Installation",
 "Sewage Ejector Pump Repair",
 "Sewer Backup Cleanup",
 "Sewer Camera Inspection",
 "Sewer Cleanout Installation",
 "Sewer Cleanout Repair",
 "Sewer Gas Testing",
 "Sewer Hydro Jetting",
 "Sewer Lateral Repair",
 "Sewer Lateral Replacement",
 "Sewer Leak Detection",
 "Sewer Line Inspection",
 "Sewer Line Repair",
 "Sewer Line Replacement",
 "Sewer Pipe Descaling",
 "Sewer Root Removal",
 "Sewer Scope Inspection",
 "Sewer Smoke Testing",
 "Shade Sail Installation",
 "Shampoo Bowl Plumbing Installation",
 "Shed Assembly",
 "Shed Demolition",
 "Shed Foundation Installation",
 "Shed Installation",
 "Shed Pad Installation",
 "Shed Relocation",
 "Shed Removal",
 "Shed Repair",
 "Sheet Metal Fabrication",
 "Sheet Metal Installation",
 "Sheet Metal Repair",
 "Shelf Installation",
 "Shingle Repair",
 "Shingle Replacement",
 "Shower Bench Installation",
 "Shower Caulking",
 "Shower Curb Installation",
 "Shower Curb Repair",
 "Shower Door Adjustment",
 "Shower Door Installation",
 "Shower Door Repair",
 "Shower Door Roller Replacement",
 "Shower Door Seal Replacement",
 "Shower Drain Repair",
 "Shower Drain Replacement",
 "Shower Installation",
 "Shower Pan Installation",
 "Shower Pan Repair",
 "Shower Repair",
 "Shower Tile Installation",
 "Shower Tile Repair",
 "Shower Valve Repair",
 "Shower Waterproofing",
 "Shower Waterproofing Repair",
 "Showerhead Installation",
 "Shrub Removal",
 "Shrub Trimming",
 "Sidewalk Cleaning",
 "Sidewalk Repair",
 "Siding Cleaning",
 "Siding Inspection",
 "Siding Installation",
 "Siding Removal",
 "Siding Repair",
 "Siding Replacement",
 "Sign Installation",
 "Sign Lighting Installation",
 "Sign Lighting Repair",
 "Sign Mounting",
 "Sink Installation",
 "Sink Reglazing",
 "Sink Repair",
 "Site Cleanup",
 "Skylight Installation",
 "Skylight Leak Repair",
 "Skylight Repair",
 "Skylight Replacement",
 "Slab Jacking",
 "Slate Roof Repair",
 "Sliding Door Alignment",
 "Sliding Door Glass Replacement",
 "Sliding Door Handle Replacement",
 "Sliding Door Installation",
 "Sliding Door Lock Replacement",
 "Sliding Door Repair",
 "Sliding Door Roller Replacement",
 "Sliding Door Screen Replacement",
 "Sliding Door Seal Replacement",
 "Sliding Door Track Replacement",
 "Slow Drain Repair",
 "Smart Appliance Setup",
 "Smart Doorbell Installation",
 "Smart Garage Door Opener Installation",
 "Smart Home Consultation",
 "Smart Home Installation",
 "Smart Home Troubleshooting",
 "Smart Irrigation Controller Installation",
 "Smart Lighting Installation",
 "Smart Lock Installation",
 "Smart Outlet Installation",
 "Smart Smoke Detector Installation",
 "Smart Switch Installation",
 "Smart Thermostat Installation",
 "Smart Water Shutoff Installation",
 "Smoke Damage Cleanup",
 "Smoke Detector Installation",
 "Smoke Detector Testing",
 "Snake Removal",
 "Sod Installation",
 "Sod Removal",
 "Sod Replacement",
 "Sofa Assembly",
 "Soffit Repair",
 "Soffit Replacement",
 "Soft Washing",
 "Soil Amendment",
 "Soil Grading",
 "Soil Removal",
 "Solar Battery Installation",
 "Solar Battery Replacement",
 "Solar Disconnect Installation",
 "Solar Disconnect Repair",
 "Solar Electrical Repair",
 "Solar Inverter Repair",
 "Solar Inverter Replacement",
 "Solar Microinverter Replacement",
 "Solar Monitoring System Repair",
 "Solar Optimizer Replacement",
 "Solar Panel Bird Proofing",
 "Solar Panel Cleaning",
 "Solar Panel Critter Guard Installation",
 "Solar Panel Detachment and Reset",
 "Solar Panel Inspection",
 "Solar Panel Installation",
 "Solar Panel Removal and Reinstallation",
 "Solar Panel Repair",
 "Solar Panel Washing",
 "Solar Roof Leak Repair",
 "Solar System Troubleshooting",
 "Solar Water Heater Installation",
 "Solar Water Heater Repair",
 "Solar Wiring Repair",
 "Soot Removal",
 "Soundbar Installation",
 "Soundproof Insulation",
 "Soundproofing Installation",
 "Spa Electrical Installation",
 "Spa Electrical Repair",
 "Spa Inspection",
 "Spa Pump Repair",
 "Speaker Installation",
 "Spider Control",
 "Spray Foam Insulation",
 "Spring Cleanup",
 "Spring Home Maintenance",
 "Sprinkler Controller Repair",
 "Sprinkler Controller Replacement",
 "Sprinkler Head Repair",
 "Sprinkler Head Replacement",
 "Sprinkler Leak Detection",
 "Sprinkler Pipe Repair",
 "Sprinkler Pipe Replacement",
 "Sprinkler Solenoid Replacement",
 "Sprinkler Start-Up Service",
 "Sprinkler System Inspection",
 "Sprinkler System Installation",
 "Sprinkler System Repair",
 "Sprinkler System Reprogramming",
 "Sprinkler System Tune-Up",
 "Sprinkler Valve Repair",
 "Sprinkler Valve Replacement",
 "Sprinkler Winterization",
 "Sprinkler Zone Repair",
 "Squeaky Floor Repair",
 "Squirrel Removal",
 "Stair Repair",
 "Staircase Installation",
 "Stairlift Installation",
 "Stairlift Repair",
 "Standard House Cleaning",
 "Standby Generator Installation",
 "Steam Shower Installation",
 "Steam Shower Repair",
 "Stone Floor Restoration",
 "Stone Installation",
 "Stone Repair",
 "Stone Veneer Repair",
 "Storage Unit Cleanout",
 "Storm Damage Cleanup",
 "Storm Debris Removal",
 "Storm Door Installation",
 "Storm Door Repair",
 "Storm Drain Cleaning",
 "Storm Drain Installation",
 "Storm Drain Repair",
 "Storm Preparation",
 "Storm Window Installation",
 "Stormwater Drainage Installation",
 "Stormwater Drainage Repair",
 "Stove Repair",
 "Structural Drying",
 "Structural Inspection",
 "Structural Reinforcement",
 "Structural Remodeling",
 "Structural Repair",
 "Structural Wood Repair",
 "Stucco Installation",
 "Stucco Painting",
 "Stucco Repair",
 "Stump Grinding",
 "Stump Hauling",
 "Stump Removal",
 "Subfloor Repair",
 "Subfloor Replacement",
 "Summer Home Maintenance",
 "Sump Pump Basin Replacement",
 "Sump Pump Battery Backup Installation",
 "Sump Pump Battery Backup Repair",
 "Sump Pump Discharge Line Installation",
 "Sump Pump Discharge Line Repair",
 "Sump Pump Installation",
 "Sump Pump Repair",
 "Sump Pump Testing",
 "Sun Tunnel Installation",
 "Sunroom Installation",
 "Sunroom Repair",
 "Sunroom Window Repair",
 "Support Beam Installation",
 "Support Beam Repair",
 "Surface Preparation",
 "Swim Spa Installation",
 "Swim Spa Repair",
 "Swing Set Assembly",
 "TV Mounting",
 "TV Mounting and Wiring",
 "TV Stand Assembly",
 "Tankless Water Heater Flushing",
 "Tankless Water Heater Installation",
 "Tankless Water Heater Maintenance",
 "Tankless Water Heater Repair",
 "Telephone Wiring",
 "Termite Inspection",
 "Termite Treatment",
 "Terrazzo Polishing",
 "Terrazzo Repair",
 "Thermal Imaging Inspection",
 "Thermal Leak Detection",
 "Thermostat Installation",
 "Thermostat Repair",
 "Threshold Removal",
 "Tick Treatment",
 "Tile Demolition",
 "Tile Floor Installation",
 "Tile Floor Repair",
 "Tile Installation",
 "Tile Polishing",
 "Tile Repair",
 "Tile Replacement",
 "Tile Roof Repair",
 "Tile Sealing",
 "Tile and Grout Cleaning",
 "Toilet Fill Valve Replacement",
 "Toilet Flush Valve Replacement",
 "Toilet Installation",
 "Toilet Repair",
 "Toilet Replacement",
 "Toilet Seat Replacement",
 "Toilet Tank Repair",
 "Toilet Tank Replacement",
 "Topsoil Installation",
 "Topsoil Replacement",
 "Trampoline Assembly",
 "Trap Primer Installation",
 "Trash Compactor Repair",
 "Trauma Scene Cleanup",
 "Travertine Restoration",
 "Treadmill Assembly",
 "Treadmill Moving",
 "Tree Crown Reduction",
 "Tree Debris Removal",
 "Tree Limb Removal",
 "Tree Pruning",
 "Tree Removal",
 "Tree Root Barrier Installation",
 "Tree Root Removal",
 "Tree Stump Disposal",
 "Tree Trimming",
 "Trench Drain Installation",
 "Trench Drain Repair",
 "Trenching",
 "Trenchless Sewer Repair",
 "Trim Installation",
 "Trim Painting",
 "Trim Repair",
 "Trimlight Installation",
 "Tub Caulking",
 "Tub Drain Repair",
 "Tub Drain Replacement",
 "Tub-to-Shower Conversion",
 "Tuckpointing",
 "Turbine Vent Installation",
 "Turbine Vent Repair",
 "USB Outlet Installation",
 "UV Air Sanitizer Installation",
 "Under-Cabinet Lighting Installation",
 "Underground Downspout Installation",
 "Underpinning",
 "Unpacking Service",
 "Upholstery Cleaning",
 "Urinal Installation",
 "Urinal Repair",
 "Utility Sink Installation",
 "Utility Sink Repair",
 "VOC Testing",
 "Vacant Property Maintenance",
 "Vacation Home Check",
 "Vacation Property Maintenance",
 "Vanity Assembly",
 "Vapor Barrier Installation",
 "Vegetation Removal",
 "Vent Cover Replacement",
 "Vent Installation",
 "Video Doorbell Installation",
 "Vine Removal",
 "Vinyl Fence Installation",
 "Vinyl Fence Repair",
 "Vinyl Flooring Installation",
 "Vinyl Flooring Repair",
 "Vinyl Siding Installation",
 "Vinyl Siding Repair",
 "Voice Assistant Setup",
 "Wainscoting Installation",
 "Walk-In Cooler Repair",
 "Walk-In Freezer Repair",
 "Walk-In Shower Installation",
 "Walk-In Tub Installation",
 "Walkway Installation",
 "Walkway Repair",
 "Wall Anchoring",
 "Wall Demolition",
 "Wall Framing",
 "Wall Insulation Installation",
 "Wall Mural Installation",
 "Wall Painting",
 "Wall Removal",
 "Wall Repair",
 "Wallpaper Installation",
 "Wallpaper Removal",
 "Wardrobe Assembly",
 "Warranty Inspection",
 "Washer Hookup Installation",
 "Washing Machine Installation",
 "Washing Machine Repair",
 "Wasp Nest Removal",
 "Water Damage Reconstruction",
 "Water Dispenser Repair",
 "Water Extraction",
 "Water Feature Installation",
 "Water Feature Repair",
 "Water Filtration System Installation",
 "Water Heater Anode Rod Replacement",
 "Water Heater Expansion Tank Installation",
 "Water Heater Expansion Tank Replacement",
 "Water Heater Flushing",
 "Water Heater Flushing Service",
 "Water Heater Heating Element Replacement",
 "Water Heater Installation",
 "Water Heater Leak Repair",
 "Water Heater Maintenance",
 "Water Heater Repair",
 "Water Heater Replacement",
 "Water Heater Thermostat Replacement",
 "Water Leak Detection",
 "Water Main Installation",
 "Water Main Repair",
 "Water Main Replacement",
 "Water Pressure Regulator Replacement",
 "Water Pressure Repair",
 "Water Service Line Repair",
 "Water Service Line Replacement",
 "Water Shutoff Valve Replacement",
 "Water Softener Installation",
 "Water Softener Repair",
 "Water-Damaged Drywall Repair",
 "Water-Damaged Flooring Repair",
 "Waterproofing Inspection",
 "Weatherproofing",
 "Weatherstripping",
 "Weatherstripping Inspection",
 "Weed Control",
 "Well Inspection",
 "Well Pressure Tank Repair",
 "Well Pressure Tank Replacement",
 "Well Pump Installation",
 "Well Pump Repair",
 "Well Pump Replacement",
 "Well Water Testing",
 "Wheelchair Lift Installation",
 "Wheelchair Lift Repair",
 "Wheelchair Ramp Installation",
 "Wheelchair Ramp Repair",
 "Whole-House Dehumidifier Installation",
 "Whole-House Fan Installation",
 "Whole-House Humidifier Installation",
 "Whole-House Painting",
 "Whole-House Renovation",
 "Whole-House Repiping",
 "Whole-House Rewiring",
 "Whole-House Ventilation Installation",
 "Whole-House Ventilation Repair",
 "Wi-Fi Camera Installation",
 "Wi-Fi Extender Installation",
 "Wi-Fi Network Setup",
 "Widened Doorway Installation",
 "Wildlife Removal",
 "Wind Mitigation Inspection",
 "Window AC Installation",
 "Window Balance Repair",
 "Window Blind Installation",
 "Window Caulking",
 "Window Cleaning",
 "Window Crank Repair",
 "Window Draft Repair",
 "Window Film Installation",
 "Window Film Removal",
 "Window Frame Repair",
 "Window Framing",
 "Window Glass Replacement",
 "Window Hardware Replacement",
 "Window Installation",
 "Window Leak Repair",
 "Window Lock Installation",
 "Window Lock Repair",
 "Window Mechanism Repair",
 "Window Painting",
 "Window Pickup and Installation",
 "Window Reglazing",
 "Window Removal",
 "Window Repair",
 "Window Replacement",
 "Window Roller Repair",
 "Window Sash Repair",
 "Window Screen Repair",
 "Window Screen Replacement",
 "Window Seal Replacement",
 "Window Security Bar Installation",
 "Window Security Bar Removal",
 "Window Shutter Installation",
 "Window Spring Replacement",
 "Window Tint Replacement",
 "Window Tinting",
 "Window Track Repair",
 "Window Trim Repair",
 "Window Trim Replacement",
 "Window Weatherstripping",
 "Window Well Cleaning",
 "Window Well Cover Installation",
 "Window Well Drainage Repair",
 "Window Well Installation",
 "Wine Cooler Repair",
 "Winter Home Maintenance",
 "Wood Fence Installation",
 "Wood Fence Repair",
 "Wood Furniture Repair",
 "Wood Paneling Repair",
 "Wood Refinishing",
 "Wood Rot Repair",
 "Wood Siding Repair",
 "Wood Staining",
 "Wood-Burning Fireplace Repair",
 "Yard Cleanup",
 "Yard Drainage Repair",
 "Yard Waste Removal"
];

const LOWER = new Map(SERVICE_NAMES.map((n) => [n.toLowerCase(), n]));
/** Returns the canonical service name for a case-insensitive match, else null. */
export function canonicalService(value: string): string | null {
  return LOWER.get(value.trim().toLowerCase()) ?? null;
}
